### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Ygarr** [LoboEvolution/LoboEvolution#110]
LoboEvolution-LoboEvolution-528d178 java: v22 $  mvn install -Dmaven.test.skip=true

mvn install -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] LoboParser                                                         [jar]
[INFO] LoboW3C                                                            [jar]
[INFO] LoboCommon                                                         [jar]
[INFO] LoboStore                                                          [jar]
[INFO] LoboApi                                                            [jar]
[INFO] LoboXalan                                                          [jar]
[INFO] LoboPDF                                                            [jar]
[INFO] LoboIViewer                                                        [jar]
[INFO] LoboJTattoo                                                        [jar]
[INFO] LoboHTML                                                           [jar]
[INFO] LoboUnitTest                                                       [jar]
[INFO] LoboJhrome                                                         [jar]
[INFO] LoboEvo                                                            [jar]
[INFO] Lobo Evolution                                                     [pom]
[INFO] 
[INFO] --------------------< org.loboevolution:LoboParser >--------------------
[INFO] Building LoboParser 1.0                                           [1/14]
[INFO]   from LoboParser/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.2.2/maven-surefire-plugin-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.2.2/maven-surefire-plugin-3.2.2.pom (5.1 kB at 8.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.2.2/surefire-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.2.2/surefire-3.2.2.pom (21 kB at 260 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.2.2/maven-surefire-plugin-3.2.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.2.2/maven-surefire-plugin-3.2.2.jar (45 kB at 469 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.1/maven-install-plugin-3.1.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.1/maven-install-plugin-3.1.1.pom (7.8 kB at 163 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.1/maven-install-plugin-3.1.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.1/maven-install-plugin-3.1.1.jar (31 kB at 539 kB/s)
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ LoboParser ---
[INFO] Copying 3 resources from src/main/resources to ../target/LoboParser/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ LoboParser ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 377 source files with javac [debug target 8] to ../target/LoboParser/classes
[WARNING] bootstrap class path is not set in conjunction with -source 8
  not setting the bootstrap class path may lead to class files that cannot run on JDK 8
    --release 8 is recommended instead of -source 8 -target 8 because it sets the bootstrap class path automatically
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/ContextFactory.java:[11,21] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/LazilyLoadedCtor.java:[11,21] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java:[18,21] java.security.AccessControlContext in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[9,21] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecureCaller.java:[13,21] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/PolicySecurityController.java:[9,21] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/PolicySecurityController.java:[11,21] java.security.Policy in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/ContextFactory.java:[341,16] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/LazilyLoadedCtor.java:[81,20] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java:[835,9] java.lang.SecurityManager in java.lang has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java:[835,36] getSecurityManager() in java.lang.System has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java:[838,32] java.security.AccessControlContext in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java:[840,23] java.security.AccessControlContext in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[23,16] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[33,16] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[50,15] java.lang.SecurityManager in java.lang has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[50,55] getSecurityManager() in java.lang.System has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecurityUtilities.java:[52,20] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecureCaller.java:[51,25] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecureCaller.java:[80,37] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/SecureCaller.java:[128,17] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/PolicySecurityController.java:[69,17] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/PolicySecurityController.java:[97,25] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/PolicySecurityController.java:[127,37] java.security.AccessController in java.security has been deprecated and marked for removal
[WARNING] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/RhinoSecurityManager.java:[14,43] java.lang.SecurityManager in java.lang has been deprecated and marked for removal
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java: Some input files use or override a deprecated API.
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/src/main/java/org/mozilla/javascript/JavaMembers.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ LoboParser ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ LoboParser ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ LoboParser ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.2.2/maven-surefire-common-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.2.2/maven-surefire-common-3.2.2.pom (6.1 kB at 108 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/3.2.2/surefire-api-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/3.2.2/surefire-api-3.2.2.pom (3.4 kB at 70 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-logger-api/3.2.2/surefire-logger-api-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-logger-api/3.2.2/surefire-logger-api-3.2.2.pom (3.2 kB at 65 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-shared-utils/3.2.2/surefire-shared-utils-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-shared-utils/3.2.2/surefire-shared-utils-3.2.2.pom (4.1 kB at 83 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.2.2/surefire-extensions-api-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.2.2/surefire-extensions-api-3.2.2.pom (3.2 kB at 70 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/3.2.2/surefire-booter-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/3.2.2/surefire-booter-3.2.2.pom (4.3 kB at 85 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-spi/3.2.2/surefire-extensions-spi-3.2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-spi/3.2.2/surefire-extensions-spi-3.2.2.pom (1.7 kB at 36 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/1.2.0/plexus-java-1.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/1.2.0/plexus-java-1.2.0.pom (4.3 kB at 87 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-languages/1.2.0/plexus-languages-1.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-languages/1.2.0/plexus-languages-1.2.0.pom (3.2 kB at 67 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/15/plexus-15.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/15/plexus-15.pom (28 kB at 471 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.2.2/maven-surefire-common-3.2.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.2.2/maven-surefire-common-3.2.2.jar (309 kB at 1.9 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/3.2.2/surefire-api-3.2.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-logger-api/3.2.2/surefire-logger-api-3.2.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.2.2/surefire-extensions-api-3.2.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/3.2.2/surefire-booter-3.2.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-spi/3.2.2/surefire-extensions-spi-3.2.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-logger-api/3.2.2/surefire-logger-api-3.2.2.jar (14 kB at 87 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/1.2.0/plexus-java-1.2.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-spi/3.2.2/surefire-extensions-spi-3.2.2.jar (8.2 kB at 50 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-shared-utils/3.2.2/surefire-shared-utils-3.2.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.2.2/surefire-extensions-api-3.2.2.jar (26 kB at 88 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/1.2.0/plexus-java-1.2.0.jar (58 kB at 152 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/3.2.2/surefire-api-3.2.2.jar (171 kB at 277 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/3.2.2/surefire-booter-3.2.2.jar (118 kB at 189 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-shared-utils/3.2.2/surefire-shared-utils-3.2.2.jar (2.3 MB at 2.9 MB/s)
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ LoboParser ---
[INFO] Building jar: /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/target/LoboParser/LoboParser-1.0.jar
[INFO] 
[INFO] --- install:3.1.1:install (default-install) @ LoboParser ---
[INFO] Installing /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboParser/pom.xml to /home/myuser/.m2/repository/org/loboevolution/LoboParser/1.0/LoboParser-1.0.pom
[INFO] Installing /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/target/LoboParser/LoboParser-1.0.jar to /home/myuser/.m2/repository/org/loboevolution/LoboParser/1.0/LoboParser-1.0.jar
[INFO] 
[INFO] ---------------------< org.loboevolution:LoboW3C >----------------------
[INFO] Building LoboW3C 1.0                                              [2/14]
[INFO]   from LoboW3C/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ LoboW3C ---
[INFO] skip non existing resourceDirectory /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ LoboW3C ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 370 source files with javac [debug target 8] to ../target/LoboW3C/classes
[WARNING] bootstrap class path is not set in conjunction with -source 8
  not setting the bootstrap class path may lead to class files that cannot run on JDK 8
    --release 8 is recommended instead of -source 8 -target 8 because it sets the bootstrap class path automatically
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/java/org/loboevolution/html/node/Element.java: Some input files use or override a deprecated API.
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/java/org/loboevolution/html/node/Element.java: Recompile with -Xlint:deprecation for details.
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/java/org/loboevolution/html/node/AbstractList.java: /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/java/org/loboevolution/html/node/AbstractList.java uses unchecked or unsafe operations.
[INFO] /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/src/main/java/org/loboevolution/html/node/AbstractList.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ LoboW3C ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ LoboW3C ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ LoboW3C ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ LoboW3C ---
[INFO] Building jar: /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/target/LoboW3C/LoboW3C-1.0.jar
[INFO] 
[INFO] --- install:3.1.1:install (default-install) @ LoboW3C ---
[INFO] Installing /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboW3C/pom.xml to /home/myuser/.m2/repository/org/loboevolution/LoboW3C/1.0/LoboW3C-1.0.pom
[INFO] Installing /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/target/LoboW3C/LoboW3C-1.0.jar to /home/myuser/.m2/repository/org/loboevolution/LoboW3C/1.0/LoboW3C-1.0.jar
[INFO] 
[INFO] --------------------< org.loboevolution:LoboCommon >--------------------
[INFO] Building LoboCommon 1.0                                           [3/14]
[INFO]   from LoboCommon/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ LoboCommon ---
[INFO] skip non existing resourceDirectory /run/media/myuser/exfatfs/java/LoboEvolution-LoboEvolution-528d178/LoboCommon/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ LoboCommon ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 58 source files with javac [debug target 8] to ../target/LoboCommon/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] LoboParser 1.0 ..................................... SUCCESS [  6.739 s]
[INFO] LoboW3C 1.0 ........................................ SUCCESS [  0.513 s]
[INFO] LoboCommon 1.0 ..................................... FAILURE [  0.250 s]
[INFO] LoboStore 1.0 ...................................... SKIPPED
[INFO] LoboApi 1.0 ........................................ SKIPPED
[INFO] LoboXalan 1.0 ...................................... SKIPPED
[INFO] LoboPDF 1.0 ........................................ SKIPPED
[INFO] LoboIViewer 1.0 .................................... SKIPPED
[INFO] LoboJTattoo 1.0 .................................... SKIPPED
[INFO] LoboHTML 1.0 ....................................... SKIPPED
[INFO] LoboUnitTest 1.0 ................................... SKIPPED
[INFO] LoboJhrome 1.0 ..................................... SKIPPED
[INFO] LoboEvo 1.0 ........................................ SKIPPED
[INFO] Lobo Evolution 4.0 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.593 s
[INFO] Finished at: 2024-05-08T11:37:40+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project LoboCommon: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :LoboCommon

**Comment by oswetto** [comment]
@Ygarr, Fixed in  [last commit](https://github.com/LoboEvolution/LoboEvolution/commit/9b3c9367c55efd0488ea180f418c8a880b0c2d46)
