### ISSUE TITLE
BSOD Within WebView 

### ISSUE THREAD

**Issue by abummoja** [LoboEvolution/LoboEvolution#112]
The web renderer displays a blue screen of death, some internal process must be faulty. I've tried contributing but I just can't get maven to work and migrating to ANT ruined my local repo.

**Comment by oswetto** [comment]
Hello @abummoja
last commit fix compile error. Any help is welcome

**Comment by abummoja** [comment]
> Hello @abummoja
> last commit fix compile error. Any help is welcome

Ok, I'll try getting maven to work on my machine though it works with ant projects. @oswetto
