### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by Sciss** [LoboEvolution/LoboEvolution#44]
Would it be possible to publish lobo evolution as a maven artifact, so it can be used as a library dependency with standard build tools on the JVM?

**Comment by Sciss** [comment]
Any news on this?

**Comment by oswetto** [comment]
In the future i fix this issue

**Comment by oswetto** [comment]
Add link for maven activity, sorry for notification

https://issues.sonatype.org/browse/OSSRH-50916
https://dzone.com/articles/publish-your-artifacts-to-maven-central

**Comment by oswetto** [comment]
Hello @Sciss 
you can add loboevolution at your maven project

<dependency>
  <groupId>com.github.oswetto</groupId>
  <artifactId>loboevolution</artifactId>
  <version>1.0</version>
</dependency>
