### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by JasonTheKitten** [LoboEvolution/LoboEvolution#63]
![image](https://user-images.githubusercontent.com/15697938/113464020-b81c4e00-93f7-11eb-9bd9-72497fccbc3a.png)
I was trying out the newest release but I noticed it was giving null exceptions.
This seems to completely prevent pages from loading.

The log says that it is a problem with your autocomplete code. The exception happens on line 93.

(I like to keep eyes on this because I like browser dev, and it happens to resemble my own attempts xD)

EDIT: It actually doesn't keep the page from loading, it seems, I just have to click the page. It's still an exception though, meaning that something is broken somewhere.

**Comment by oswetto** [comment]
Hello @JasonTheKitten thanks for report. 
 Issue is fixed in last commit and update release Lobo Evolution 2.0
