### ISSUE TITLE
Cannot run with mvn

### ISSUE THREAD

**Issue by Ygarr** [LoboEvolution/LoboEvolution#76]
failing at this:
 [INFO] LoboJhrome 1.0 ..................................... FAILURE [  0.427 s]

LoboEvolution/LoboJhrome/src/main/java/org/sexydock/tabs/DefaultFloatingTabHandler.java:[22,19] package com.sun.awt does not exist

**Comment by oswetto** [comment]
Hell @Ygarr thanks for yuor test. LoboEvolution work only with java 8. 

The com.sun.awt.AWTUtilities class was deprecated with forRemoval=true in JDK 10 ([JDK-8187253](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8187253)). This class was unused in the JDK and has been removed in this release. https://www.oracle.com/java/technologies/javase/11-relnote-issues.html

**Comment by oswetto** [comment]
Fixed in last commit. Thansk for you test
