### ISSUE TITLE
UI Showing Nothing for a Simple Google Search

### ISSUE THREAD

**Issue by lynnwilliam** [LoboEvolution/LoboEvolution#79]
Dev
1. downloaded the jar file 3.0
2. ran the jar file using "java -jar  loboevolution-3.0.jar"
3. Entered "Hello world" into the address bar and pressed enter.
here is the terminal result

Sep 28, 2022 7:39:14 PM org.loboevolution.html.gui.HtmlPanel createHtmlPanel
SEVERE: Server returned HTTP response code: 403 for URL: https://www.google.com/search?q=hello%20world
java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.google.com/search?q=hello%20world

**Comment by proplayer919** [comment]
This is an internal error with google.com. Google denies access to unknown sources.

**Comment by oswetto** [comment]
@lynnwilliam Bug fixed, but google won't open... Js by default is disabled because support is more bugged

**Comment by lynnwilliam** [comment]
But if JS is disabled in the browser, it can't really be used as a browser. Does it have full JS support?

**Comment by oswetto** [comment]
With last commits Google page works.
To enable  javascript go Tab tools --> Preferencs --> General ---> Enabled Javascript --> Apply --> ok
