### ISSUE TITLE
HTML viewer has tightly coupled dependencies

### ISSUE THREAD

**Issue by DaveJarvis** [LoboEvolution/LoboEvolution#83]
LoboEvolution has the potential to be a vast improvement over FlyingSaucer and JavaFX WebView. There are a few architectural issues that introduce tight-coupling between components, such as:

* **LoboHTML -> LoboPDF.** Coupling a PDF viewer within an HTML browser isn't necessary. (And could be considered a slight reinvention of the wheel, given that most desktops have a PDF viewer already.) For example, KeenWrite is a Markdown editor that has an in-app HTML preview window. Users do not need to view a PDF inside of KeenWrite because KeenWrite exports the content to a typesetting engine. The results are loaded in a desktop PDF viewer. Forcing a PDF renderer to be included in the HTML renderer is an unnecessary coupling that, IMO, limits its usage.

* **LoboHTML -> JavaScript.** While most browsers are useless these days without JavaScript, there are situations where no JavaScript is required. For example, when converting Markdown to (X)HTML for subsequent rendering, there's no need to bundle the complexity of JavaScript.

* **LoboHTML -> Storage.** Besides JavaScript storage, there are other places in the LoboHTML project that are coupled to storage. Such as, navigation history, tabs, and window preference sizes. A basic HTML renderer does not need that functionality. Rather, that would be the responsibility of LoboEvo. KeenWrite, for example, has its own tabbed interface using dockable tabs, and the HTML preview panel does not need navigation abilities (no tabs, no visited hyperlinks, no window size preferences).

Here are some suggestions for how to resolve some of these issues:

* Create **LoboStorage** package then move all storage-related classes (GeneralStorage, SessionStorage, etc.) into that package. All persistence-related data would need to move into LoboEvo. As a stop-gap, storage interfaces could be created and injected. A fake/empty implementation could be provided by default.
* Create **LoboJavaScript** package then move all JavaScript-related functionality into that package. LoboEvo would be responsible for gluing together the DOM modifications by LoboJavaScript against LoboHTML.
* When a hyperlink is clicked, have the LoboHTML fire an event that listeners may consume to perform an action. That would allow LoboEvo to detect clicks on PDF files and replace the content with a PDF using the PdfViewer, without having to introduce that functionality into LoboHTML. This is how KeenWrite [integrates](https://github.com/DaveJarvis/keenwrite/blob/6fa925d27bbec807fc4419454aa81941524f889f/src/main/java/com/keenwrite/preview/FlyingSaucerPanel.java#L65) with FlyingSaucer from the [MainApp](https://github.com/DaveJarvis/keenwrite/blob/2e0e4dc71975a815f33b56a74cd6794ecdf15cf6/src/main/java/com/keenwrite/MainApp.java#L193) without tightly coupling FlyingSaucer to a PDF viewer.

Overall, I'm looking for a simple pure Java HTML renderer that can replace FlyingSaucer for rendering Markdown documents. Something modern with abilities to display HTML and CSS3, but without the bloat of PDF and JavaScript. LoboHTML comes quite close. (If there was a JavaFX integration to replace JavaFX WebView, that would be ideal.)

**Comment by lynnwilliam** [comment]
I agree, having the DB stuff tightly coupled means I can't use this repo in my own projects.
I don't require or need any DB storage or sql stuff

**Comment by oswetto** [comment]
Created new project CobraEvolution, Html Render and Parser without browser dependency
https://github.com/LoboEvolution/CobraEvolution
