### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by DaveJarvis** [LoboEvolution/LoboEvolution#84]
Consider adding a BUILD.md file that contains instructions for how to build various components. For example, I was looking for instructions about on building the LoboHTML component to see whether it was suitable for inclusion in KeenWrite. Here are the instructions I crafted, in case they may be useful:

``` markdown
git clone https://github.com/LoboEvolution/LoboEvolution
cd LoboEvolution/LoboParser
mvn clean package install
cd ../LoboW3C
mvn clean package install
cd ../LoboCommon
mvn clean package install
cd ../LoboIViewer
mvn clean package install
cd ../LoboXalan
mvn clean package install
cd ../LoboApi
mvn clean package install
cd ../LoboHTML
mvn clean package install
```

**Comment by oswetto** [comment]
Created new project CobraEvolution, Html Render and Parser without browser dependency
https://github.com/LoboEvolution/CobraEvolution
