### ISSUE TITLE
⚠️Tester - Help Wanted⚠️

### ISSUE THREAD

**Issue by oswetto** [LoboEvolution/LoboEvolution#91]
Hello Tester! I am in need of people to help me to test, report bug, and fix LoboEvolution

Step 0
Run unit test present in sub-project [LoboUnitTest](https://github.com/LoboEvolution/LoboEvolution/tree/master/LoboUnitTest)
see the error and try to fix it

Step1 
git clone this repo.
Download the [CSS2.1 testsuite](http://test.csswg.org/suites/css21_dev/) from w3c. or Download the [Test suites for Web-platform specs](https://github.com/w3c/web-platform-tests/)

Run [PlatformInit.java](https://github.com/oswetto/LoboEvolution/blob/master/LoboEvo/src/main/java/org/loboevolution/init/PlatformInit.java)
Test file
Report bug
And... find solution and push [pull requests](https://help.github.com/articles/about-pull-requests/)

Step 2 - **Only for the Brave**
Run [PlatformInit.java]
Test real web site

**Comment by evabth** [comment]
Hey, I'd like to help with your posting, though, I am a newbie to helping on github. I have most of my experience in java coding which I believe is what your project is mostly coded in. With that being said, I'm not exactly sure where to start, so if you could give me some guidance on that, that would be great.

**Comment by oswetto** [comment]
Hi @evabth To start with the project, you can see the LoboUnitTest subproject where the unit tests are. You can run tests, see errors, and try to fix them

**Comment by evabth** [comment]
Thanks, When importing the project onto my own machine, when trying to create a local build of the project, the LoboParser is presenting issues

![errorPic](https://github.com/LoboEvolution/LoboEvolution/assets/97984540/20c046f8-9fec-4bc6-8653-7f4ab4352bca)
